//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterface) DeepCopyInto(out *NetlinkInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterface.
func (in *NetlinkInterface) DeepCopy() *NetlinkInterface {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetlinkInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceAddressSpec) DeepCopyInto(out *NetlinkInterfaceAddressSpec) {
	*out = *in
	if in.PeerCIDR != nil {
		in, out := &in.PeerCIDR, &out.PeerCIDR
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceAddressSpec.
func (in *NetlinkInterfaceAddressSpec) DeepCopy() *NetlinkInterfaceAddressSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceAddressStatus) DeepCopyInto(out *NetlinkInterfaceAddressStatus) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceAddressStatus.
func (in *NetlinkInterfaceAddressStatus) DeepCopy() *NetlinkInterfaceAddressStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceAddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceAddressStatusWrapper) DeepCopyInto(out *NetlinkInterfaceAddressStatusWrapper) {
	*out = *in
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceAddressStatusWrapper.
func (in *NetlinkInterfaceAddressStatusWrapper) DeepCopy() *NetlinkInterfaceAddressStatusWrapper {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceAddressStatusWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceBridgeSpec) DeepCopyInto(out *NetlinkInterfaceBridgeSpec) {
	*out = *in
	if in.Slaves != nil {
		in, out := &in.Slaves, &out.Slaves
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceBridgeSpec.
func (in *NetlinkInterfaceBridgeSpec) DeepCopy() *NetlinkInterfaceBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceBridgeStatus) DeepCopyInto(out *NetlinkInterfaceBridgeStatus) {
	*out = *in
	if in.EnslavedLinks != nil {
		in, out := &in.EnslavedLinks, &out.EnslavedLinks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceBridgeStatus.
func (in *NetlinkInterfaceBridgeStatus) DeepCopy() *NetlinkInterfaceBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceContainerDockerSpec) DeepCopyInto(out *NetlinkInterfaceContainerDockerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceContainerDockerSpec.
func (in *NetlinkInterfaceContainerDockerSpec) DeepCopy() *NetlinkInterfaceContainerDockerSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceContainerDockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceContainerNetNSSpec) DeepCopyInto(out *NetlinkInterfaceContainerNetNSSpec) {
	*out = *in
	if in.PID != nil {
		in, out := &in.PID, &out.PID
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceContainerNetNSSpec.
func (in *NetlinkInterfaceContainerNetNSSpec) DeepCopy() *NetlinkInterfaceContainerNetNSSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceContainerNetNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceContainerSpec) DeepCopyInto(out *NetlinkInterfaceContainerSpec) {
	*out = *in
	if in.NetNS != nil {
		in, out := &in.NetNS, &out.NetNS
		*out = new(NetlinkInterfaceContainerNetNSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(NetlinkInterfaceContainerDockerSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceContainerSpec.
func (in *NetlinkInterfaceContainerSpec) DeepCopy() *NetlinkInterfaceContainerSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceDummySpec) DeepCopyInto(out *NetlinkInterfaceDummySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceDummySpec.
func (in *NetlinkInterfaceDummySpec) DeepCopy() *NetlinkInterfaceDummySpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceDummySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceList) DeepCopyInto(out *NetlinkInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetlinkInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceList.
func (in *NetlinkInterfaceList) DeepCopy() *NetlinkInterfaceList {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetlinkInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceSpec) DeepCopyInto(out *NetlinkInterfaceSpec) {
	*out = *in
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = new(NetlinkInterfaceBridgeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Vxlan != nil {
		in, out := &in.Vxlan, &out.Vxlan
		*out = new(NetlinkInterfaceVxlanSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Dummy != nil {
		in, out := &in.Dummy, &out.Dummy
		*out = new(NetlinkInterfaceDummySpec)
		**out = **in
	}
	if in.Veth != nil {
		in, out := &in.Veth, &out.Veth
		*out = new(NetlinkInterfaceVethSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]NetlinkInterfaceAddressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(NetlinkInterfaceContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceSpec.
func (in *NetlinkInterfaceSpec) DeepCopy() *NetlinkInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceStatus) DeepCopyInto(out *NetlinkInterfaceStatus) {
	*out = *in
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Netlink != nil {
		in, out := &in.Netlink, &out.Netlink
		*out = new(NetlinkStatusWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = new(NetlinkInterfaceBridgeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Veth != nil {
		in, out := &in.Veth, &out.Veth
		*out = new(NetlinkInterfaceVethStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceStatus.
func (in *NetlinkInterfaceStatus) DeepCopy() *NetlinkInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceVethPeerSpec) DeepCopyInto(out *NetlinkInterfaceVethPeerSpec) {
	*out = *in
	if in.InterfaceName != nil {
		in, out := &in.InterfaceName, &out.InterfaceName
		*out = new(string)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]NetlinkInterfaceAddressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(NetlinkInterfaceContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceVethPeerSpec.
func (in *NetlinkInterfaceVethPeerSpec) DeepCopy() *NetlinkInterfaceVethPeerSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceVethPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceVethPeerStatus) DeepCopyInto(out *NetlinkInterfaceVethPeerStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceVethPeerStatus.
func (in *NetlinkInterfaceVethPeerStatus) DeepCopy() *NetlinkInterfaceVethPeerStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceVethPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceVethSpec) DeepCopyInto(out *NetlinkInterfaceVethSpec) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(NetlinkInterfaceVethPeerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(NetlinkInterfaceVethPeerSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceVethSpec.
func (in *NetlinkInterfaceVethSpec) DeepCopy() *NetlinkInterfaceVethSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceVethSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceVethStatus) DeepCopyInto(out *NetlinkInterfaceVethStatus) {
	*out = *in
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(NetlinkInterfaceVethPeerStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceVethStatus.
func (in *NetlinkInterfaceVethStatus) DeepCopy() *NetlinkInterfaceVethStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceVethStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceVxlanSpec) DeepCopyInto(out *NetlinkInterfaceVxlanSpec) {
	*out = *in
	if in.Dev != nil {
		in, out := &in.Dev, &out.Dev
		*out = new(string)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int)
		**out = **in
	}
	if in.TOS != nil {
		in, out := &in.TOS, &out.TOS
		*out = new(int)
		**out = **in
	}
	if in.ProxyARP != nil {
		in, out := &in.ProxyARP, &out.ProxyARP
		*out = new(bool)
		**out = **in
	}
	if in.NoAge != nil {
		in, out := &in.NoAge, &out.NoAge
		*out = new(bool)
		**out = **in
	}
	if in.PortRange != nil {
		in, out := &in.PortRange, &out.PortRange
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceVxlanSpec.
func (in *NetlinkInterfaceVxlanSpec) DeepCopy() *NetlinkInterfaceVxlanSpec {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceVxlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkStatisticsWrapper) DeepCopyInto(out *NetlinkStatisticsWrapper) {
	*out = *in
	out.LinkStatistics = in.LinkStatistics
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkStatisticsWrapper.
func (in *NetlinkStatisticsWrapper) DeepCopy() *NetlinkStatisticsWrapper {
	if in == nil {
		return nil
	}
	out := new(NetlinkStatisticsWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkStatusWrapper) DeepCopyInto(out *NetlinkStatusWrapper) {
	*out = *in
	if in.AltNames != nil {
		in, out := &in.AltNames, &out.AltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = new(NetlinkStatisticsWrapper)
		**out = **in
	}
	if in.Addrs != nil {
		in, out := &in.Addrs, &out.Addrs
		*out = make([]NetlinkInterfaceAddressStatusWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkStatusWrapper.
func (in *NetlinkStatusWrapper) DeepCopy() *NetlinkStatusWrapper {
	if in == nil {
		return nil
	}
	out := new(NetlinkStatusWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocol) DeepCopyInto(out *OSPFProtocol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocol.
func (in *OSPFProtocol) DeepCopy() *OSPFProtocol {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OSPFProtocol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocolAreaStatus) DeepCopyInto(out *OSPFProtocolAreaStatus) {
	*out = *in
	if in.Backbone != nil {
		in, out := &in.Backbone, &out.Backbone
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocolAreaStatus.
func (in *OSPFProtocolAreaStatus) DeepCopy() *OSPFProtocolAreaStatus {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocolAreaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocolInterfaceSpec) DeepCopyInto(out *OSPFProtocolInterfaceSpec) {
	*out = *in
	if in.Passive != nil {
		in, out := &in.Passive, &out.Passive
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocolInterfaceSpec.
func (in *OSPFProtocolInterfaceSpec) DeepCopy() *OSPFProtocolInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocolInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocolList) DeepCopyInto(out *OSPFProtocolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OSPFProtocol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocolList.
func (in *OSPFProtocolList) DeepCopy() *OSPFProtocolList {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OSPFProtocolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocolSpec) DeepCopyInto(out *OSPFProtocolSpec) {
	*out = *in
	if in.VRF != nil {
		in, out := &in.VRF, &out.VRF
		*out = new(string)
		**out = **in
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]OSPFProtocolInterfaceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocolSpec.
func (in *OSPFProtocolSpec) DeepCopy() *OSPFProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSPFProtocolStatus) DeepCopyInto(out *OSPFProtocolStatus) {
	*out = *in
	if in.RouterId != nil {
		in, out := &in.RouterId, &out.RouterId
		*out = new(string)
		**out = **in
	}
	if in.Areas != nil {
		in, out := &in.Areas, &out.Areas
		*out = make([]OSPFProtocolAreaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VRF != nil {
		in, out := &in.VRF, &out.VRF
		*out = new(string)
		**out = **in
	}
	if in.Driver != nil {
		in, out := &in.Driver, &out.Driver
		*out = new(OSPFProtocolDriverType)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(OSPFProtocolVersion)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSPFProtocolStatus.
func (in *OSPFProtocolStatus) DeepCopy() *OSPFProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(OSPFProtocolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStatus) DeepCopyInto(out *PeerStatus) {
	*out = *in
	if in.LatestHandshake != nil {
		in, out := &in.LatestHandshake, &out.LatestHandshake
		*out = new(int64)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStatus.
func (in *PeerStatus) DeepCopy() *PeerStatus {
	if in == nil {
		return nil
	}
	out := new(PeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeySecretRef) DeepCopyInto(out *PrivateKeySecretRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeySecretRef.
func (in *PrivateKeySecretRef) DeepCopy() *PrivateKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(PrivateKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterface) DeepCopyInto(out *WireGuardInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterface.
func (in *WireGuardInterface) DeepCopy() *WireGuardInterface {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceAddressSpec) DeepCopyInto(out *WireGuardInterfaceAddressSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceAddressSpec.
func (in *WireGuardInterfaceAddressSpec) DeepCopy() *WireGuardInterfaceAddressSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerDockerSpec) DeepCopyInto(out *WireGuardInterfaceContainerDockerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerDockerSpec.
func (in *WireGuardInterfaceContainerDockerSpec) DeepCopy() *WireGuardInterfaceContainerDockerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerDockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerNetNSSpec) DeepCopyInto(out *WireGuardInterfaceContainerNetNSSpec) {
	*out = *in
	if in.PID != nil {
		in, out := &in.PID, &out.PID
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerNetNSSpec.
func (in *WireGuardInterfaceContainerNetNSSpec) DeepCopy() *WireGuardInterfaceContainerNetNSSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerNetNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerSpec) DeepCopyInto(out *WireGuardInterfaceContainerSpec) {
	*out = *in
	if in.NetNS != nil {
		in, out := &in.NetNS, &out.NetNS
		*out = new(WireGuardInterfaceContainerNetNSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(WireGuardInterfaceContainerDockerSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerSpec.
func (in *WireGuardInterfaceContainerSpec) DeepCopy() *WireGuardInterfaceContainerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceList) DeepCopyInto(out *WireGuardInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuardInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceList.
func (in *WireGuardInterfaceList) DeepCopy() *WireGuardInterfaceList {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceSpec) DeepCopyInto(out *WireGuardInterfaceSpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(WireGuardInterfaceContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKeySecretRef != nil {
		in, out := &in.PrivateKeySecretRef, &out.PrivateKeySecretRef
		*out = new(PrivateKeySecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]WireGuardInterfaceAddressSpec, len(*in))
		copy(*out, *in)
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]WireGuardPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceSpec.
func (in *WireGuardInterfaceSpec) DeepCopy() *WireGuardInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceStatus) DeepCopyInto(out *WireGuardInterfaceStatus) {
	*out = *in
	if in.WireGuard != nil {
		in, out := &in.WireGuard, &out.WireGuard
		*out = new(WireGuardStatusWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Netlink != nil {
		in, out := &in.Netlink, &out.Netlink
		*out = new(NetlinkStatusWrapper)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceStatus.
func (in *WireGuardInterfaceStatus) DeepCopy() *WireGuardInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlan) DeepCopyInto(out *WireGuardNetworkPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlan.
func (in *WireGuardNetworkPlan) DeepCopy() *WireGuardNetworkPlan {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardNetworkPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanInterfaceStatus) DeepCopyInto(out *WireGuardNetworkPlanInterfaceStatus) {
	*out = *in
	if in.LastHandshake != nil {
		in, out := &in.LastHandshake, &out.LastHandshake
		*out = new(int64)
		**out = **in
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(string)
		**out = **in
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanInterfaceStatus.
func (in *WireGuardNetworkPlanInterfaceStatus) DeepCopy() *WireGuardNetworkPlanInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanLinkPeerSpec) DeepCopyInto(out *WireGuardNetworkPlanLinkPeerSpec) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]WireGuardInterfaceAddressSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanLinkPeerSpec.
func (in *WireGuardNetworkPlanLinkPeerSpec) DeepCopy() *WireGuardNetworkPlanLinkPeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanLinkPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanLinkSpec) DeepCopyInto(out *WireGuardNetworkPlanLinkSpec) {
	*out = *in
	if in.ToNodes != nil {
		in, out := &in.ToNodes, &out.ToNodes
		*out = make([]WireGuardNetworkPlanLinkPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanLinkSpec.
func (in *WireGuardNetworkPlanLinkSpec) DeepCopy() *WireGuardNetworkPlanLinkSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanList) DeepCopyInto(out *WireGuardNetworkPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuardNetworkPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanList.
func (in *WireGuardNetworkPlanList) DeepCopy() *WireGuardNetworkPlanList {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardNetworkPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanNodeSpec) DeepCopyInto(out *WireGuardNetworkPlanNodeSpec) {
	*out = *in
	if in.Underlay != nil {
		in, out := &in.Underlay, &out.Underlay
		*out = new(WireGuardNetworkPlanUnderlaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(string)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(PrivateKeySecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(WireGuardInterfaceContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]WireGuardInterfaceAddressSpec, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanNodeSpec.
func (in *WireGuardNetworkPlanNodeSpec) DeepCopy() *WireGuardNetworkPlanNodeSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanPortRangeSpec) DeepCopyInto(out *WireGuardNetworkPlanPortRangeSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanPortRangeSpec.
func (in *WireGuardNetworkPlanPortRangeSpec) DeepCopy() *WireGuardNetworkPlanPortRangeSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanPortRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanSpec) DeepCopyInto(out *WireGuardNetworkPlanSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]WireGuardNetworkPlanNodeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DefaultPortRange = in.DefaultPortRange
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]WireGuardNetworkPlanLinkSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanSpec.
func (in *WireGuardNetworkPlanSpec) DeepCopy() *WireGuardNetworkPlanSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanStatus) DeepCopyInto(out *WireGuardNetworkPlanStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]WireGuardNetworkPlanInterfaceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanStatus.
func (in *WireGuardNetworkPlanStatus) DeepCopy() *WireGuardNetworkPlanStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardNetworkPlanUnderlaySpec) DeepCopyInto(out *WireGuardNetworkPlanUnderlaySpec) {
	*out = *in
	if in.PortRange != nil {
		in, out := &in.PortRange, &out.PortRange
		*out = new(WireGuardNetworkPlanPortRangeSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardNetworkPlanUnderlaySpec.
func (in *WireGuardNetworkPlanUnderlaySpec) DeepCopy() *WireGuardNetworkPlanUnderlaySpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardNetworkPlanUnderlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerSpec) DeepCopyInto(out *WireGuardPeerSpec) {
	*out = *in
	if in.PresharedKeySecretRef != nil {
		in, out := &in.PresharedKeySecretRef, &out.PresharedKeySecretRef
		*out = new(PrivateKeySecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.PersistentKeepalive != nil {
		in, out := &in.PersistentKeepalive, &out.PersistentKeepalive
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerSpec.
func (in *WireGuardPeerSpec) DeepCopy() *WireGuardPeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerStatus) DeepCopyInto(out *WireGuardPeerStatus) {
	*out = *in
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.PresharedKey != nil {
		in, out := &in.PresharedKey, &out.PresharedKey
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.PersistentKeepaliveInterval != nil {
		in, out := &in.PersistentKeepaliveInterval, &out.PersistentKeepaliveInterval
		*out = new(int64)
		**out = **in
	}
	if in.LastHandshakeTime != nil {
		in, out := &in.LastHandshakeTime, &out.LastHandshakeTime
		*out = new(int64)
		**out = **in
	}
	if in.ReceiveBytes != nil {
		in, out := &in.ReceiveBytes, &out.ReceiveBytes
		*out = new(int64)
		**out = **in
	}
	if in.TransmitBytes != nil {
		in, out := &in.TransmitBytes, &out.TransmitBytes
		*out = new(int64)
		**out = **in
	}
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerStatus.
func (in *WireGuardPeerStatus) DeepCopy() *WireGuardPeerStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardStatusWrapper) DeepCopyInto(out *WireGuardStatusWrapper) {
	*out = *in
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(string)
		**out = **in
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int)
		**out = **in
	}
	if in.FirewallMark != nil {
		in, out := &in.FirewallMark, &out.FirewallMark
		*out = new(int)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]*WireGuardPeerStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(WireGuardPeerStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardStatusWrapper.
func (in *WireGuardStatusWrapper) DeepCopy() *WireGuardStatusWrapper {
	if in == nil {
		return nil
	}
	out := new(WireGuardStatusWrapper)
	in.DeepCopyInto(out)
	return out
}
