//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkInterfaceAddressStatus) DeepCopyInto(out *NetlinkInterfaceAddressStatus) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkInterfaceAddressStatus.
func (in *NetlinkInterfaceAddressStatus) DeepCopy() *NetlinkInterfaceAddressStatus {
	if in == nil {
		return nil
	}
	out := new(NetlinkInterfaceAddressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStatus) DeepCopyInto(out *PeerStatus) {
	*out = *in
	if in.LatestHandshake != nil {
		in, out := &in.LatestHandshake, &out.LatestHandshake
		*out = new(int64)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStatus.
func (in *PeerStatus) DeepCopy() *PeerStatus {
	if in == nil {
		return nil
	}
	out := new(PeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeySecretRef) DeepCopyInto(out *PrivateKeySecretRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeySecretRef.
func (in *PrivateKeySecretRef) DeepCopy() *PrivateKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(PrivateKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterface) DeepCopyInto(out *WireGuardInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterface.
func (in *WireGuardInterface) DeepCopy() *WireGuardInterface {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceAddressSpec) DeepCopyInto(out *WireGuardInterfaceAddressSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceAddressSpec.
func (in *WireGuardInterfaceAddressSpec) DeepCopy() *WireGuardInterfaceAddressSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerDockerSpec) DeepCopyInto(out *WireGuardInterfaceContainerDockerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerDockerSpec.
func (in *WireGuardInterfaceContainerDockerSpec) DeepCopy() *WireGuardInterfaceContainerDockerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerDockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerNetNSSpec) DeepCopyInto(out *WireGuardInterfaceContainerNetNSSpec) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PID != nil {
		in, out := &in.PID, &out.PID
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerNetNSSpec.
func (in *WireGuardInterfaceContainerNetNSSpec) DeepCopy() *WireGuardInterfaceContainerNetNSSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerNetNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceContainerSpec) DeepCopyInto(out *WireGuardInterfaceContainerSpec) {
	*out = *in
	if in.NetNS != nil {
		in, out := &in.NetNS, &out.NetNS
		*out = new(WireGuardInterfaceContainerNetNSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(WireGuardInterfaceContainerDockerSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceContainerSpec.
func (in *WireGuardInterfaceContainerSpec) DeepCopy() *WireGuardInterfaceContainerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceList) DeepCopyInto(out *WireGuardInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuardInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceList.
func (in *WireGuardInterfaceList) DeepCopy() *WireGuardInterfaceList {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceSpec) DeepCopyInto(out *WireGuardInterfaceSpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(WireGuardInterfaceContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKeySecretRef != nil {
		in, out := &in.PrivateKeySecretRef, &out.PrivateKeySecretRef
		*out = new(PrivateKeySecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]WireGuardInterfaceAddressSpec, len(*in))
		copy(*out, *in)
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]WireGuardPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceSpec.
func (in *WireGuardInterfaceSpec) DeepCopy() *WireGuardInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardInterfaceStatus) DeepCopyInto(out *WireGuardInterfaceStatus) {
	*out = *in
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]NetlinkInterfaceAddressStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardInterfaceStatus.
func (in *WireGuardInterfaceStatus) DeepCopy() *WireGuardInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerSpec) DeepCopyInto(out *WireGuardPeerSpec) {
	*out = *in
	if in.PresharedKeySecretRef != nil {
		in, out := &in.PresharedKeySecretRef, &out.PresharedKeySecretRef
		*out = new(PrivateKeySecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.PersistentKeepalive != nil {
		in, out := &in.PersistentKeepalive, &out.PersistentKeepalive
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerSpec.
func (in *WireGuardPeerSpec) DeepCopy() *WireGuardPeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerSpec)
	in.DeepCopyInto(out)
	return out
}
