apiVersion: networking.dn42.io/v1alpha1
kind: NetlinkInterface
metadata:
  name: lax1-nl1-dummy
  finalizers:
    - netlinkinterface.networking.dn42.io/finalizer
  namespace: default
spec:
  node: lax1
  interfaceName: nl1-dummy
  type: dummy
  dummy: {}
  addresses:
    - ipcidr: "10.2.3.0/24"
    - ipcidr: "10.99.3.1"
      peerCidr: "10.99.4.1/32"
  mtu: 1420
  up: true
  container:
    docker:
      name: agent1
