apiVersion: networking.dn42.io/v1alpha1
kind: OSPFProtocol
metadata:
  # note: ospf1.yaml and ospf2.yaml use the same name but different spec.
  name: lax1-ospf-test-cfg
  finalizers:
    - ospfprotocol.networking.dn42.io/finalizer
  namespace: default
spec:
  node: wien1
  driver: frr
  version: v2
  interfaces:
  # vrf default (aka. default vrf)
  - interfaceName: dummy-wien1
    area: 0.0.0.0
    passive: true
    vrf: default
  - interfaceName: wg-wien1-frank1
    area: 0.0.0.0
    networkType: point-to-point
    vrf: default
  - interfaceName: wg-wien1-mnz1
    area: 0.0.0.0
    networkType: point-to-point
    vrf: default
  - interfaceName: wg-wien1-sgp1
    area: 0.0.0.0
    networkType: point-to-point
    vrf: default
  
  routers:
  - routerID: 10.3.82.1
    vrf: default

  